# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 20
  - name: Publications
    url: publication/
    weight: 30
  - name: Courses
    url: courses/
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 60
  - name: Posts
    url: '#posts'
    weight: 50
  - name: Data visualization
    url: 'Visualizations/'
    weight: 70
  - name: ShinyApps
    url: 'shiny/'
    weight: 80
    
